server:
  port: 8081

spring:
  application:
    name: kafka-consumer
  kafka:
    bootstrap-servers: http://localhost:19092
    template:
      default-topic: messagingTopic
    consumer:
      group-id: consumerId